categories = {
     "Animals": {
        "easy": ["cat", "dog", "fish", "cow", "horse", "duck", "bird", "sheep", "pig", "rabbit",
                 "goat", "lion", "tiger", "elephant", "monkey", "giraffe", "bear", "kangaroo", 
                 "panda", "whale", "shark", "frog", "owl", "deer", "zebra", "bat", "snake", 
                 "bee", "ant", "mouse", "lizard", "seal", "penguin", "pigeon", "hamster", 
                 "guinea pig", "duckling", "kitten", "puppy", "donkey", "chicken", 
                 "turkey", "swan", "eagle", "parrot", "camel", "flamingo", "raccoon", 
                 "koala", "walrus", "bison", "yak", "moose", "beetle", "butterfly", "caterpillar", 
                 "spider", "crab", "shrimp", "starfish", "octopus", "squid", "jellyfish", 
                 "lobster", "plankton", "eel", "turtle", "hedgehog", "ferret", "skunk", 
                 "otter", "chipmunk", "armadillo", "sloth", "vulture", "goose", "flounder", 
                 "bass", "trout", "salmon", "pike", "cod", "catfish"
        ],
        "medium": ["alligator", "crocodile", "hippopotamus", "rhinoceros", "gibbon", "chimpanzee", 
                   "gorilla", "orangutan", "leopard", "cheetah", "hyena", "jackal", "moose", 
                   "elk", "wolverine", "bobcat", "mountain lion", "snow leopard", "lemur", 
                   "mole", "badger", "otter", "weasel", "ermine", "martin", "coati", "ringtail", 
                   "serval", "coyote", "caracal", "puma", "ocelot", "piranha", "anglerfish", 
                   "swordfish", "barracuda", "manta ray", "stingray", "marlin", "ray", "dolphin", 
                   "porpoise", "manatee", "sea lion", "otterhound", "greyhound", "pointer", 
                   "spaniel", "retriever", "mastiff", "boxer", "bulldog", "chihuahua", "dalmatian", 
                   "poodle", "rottweiler", "husky", "schnauzer", "beagle", "pomeranian", "terrier", 
                   "cocker spaniel", "cavalier king charles spaniel", "shih tzu", "maltese", 
                   "yorkshire terrier", "basset hound", "chow chow", "collie", "whippet", "pug", 
                   "boston terrier", "papillon", "tibetan mastiff", "border collie", "labrador", 
                   "golden retriever"
        ],
        "hard": ["axolotl", "australian shepherd", "binturong", "blowfish", "blue whale", 
                 "brazilian wandering spider", "caecilian", "caique", "capybara", "cassowary", 
                 "chameleon", "china black-tipped deer", "chupacabra", "cuscus", "dugong", 
                 "dybowski's sika deer", "echidna", "elephant seal", "emperor penguin", "fossa", 
                 "galapagos tortoise", "gecko", "gerbil", "gila monster", "goliath beetle", 
                 "goral", "great white shark", "hagfish", "hummingbird", "impala", "indigo bunting", 
                 "isopod", "jaguarundi", "jellyfish", "kakapo", "kinkajou", "king vulture", 
                 "komodo dragon", "kudu", "lappet-faced vulture", "leafcutter ant", "leech", 
                 "longhorn beetle", "lynx", "maned wolf", "mantis shrimp", "marsupial mole", 
                 "moose", "musk ox", "numbat", "ocelot", "opossum", "orchid mantis", "oryx", 
                 "otterhound", "oxpecker", "pangolin", "paraceratherium", "pika", "platypus", 
                 "poison dart frog", "portuguese man o' war", "praying mantis", "pygmy hippopotamus", 
                 "quokka", "quoll", "raijū", "rakali", "red panda", "redback spider", "reindeer", 
                 "renosterveld", "sabre-toothed tiger", "saltwater crocodile", "saola", "scorpionfish", 
                 "shovel-nosed leopard lizard", "slender loris", "slow loris", "solenodons", 
                 "spiny anteater", "squid", "star-nosed mole", "superb lyrebird", "tahr", "tanuki", 
                 "tasmanian tiger", "tasselled wobbegong", "taunting crab", "texas horned lizard", 
                 "toad", "tortoise", "tuatara", "vampire bat", "vicuña", "volcano rabbit", "warthog", 
                 "water buffalo", "wolverine", "yellow-eyed penguin", "yeti crab", "zebu", "zokor", "zorse"
        ],
    },
    
     "Sports": {
        "easy": [
            "soccer", "basketball", "baseball", "football", "tennis", "golf", "swimming", "volleyball", 
            "cycling", "boxing", "skiing", "running", "hockey", "rugby", "track", "rowing", "fishing", 
            "badminton", "cricket", "archery", "ping pong", "horse racing", "surfing", "wrestling", "karate", 
            "skating", "gymnastics", "paddle", "sailing", "kickball", "softball", "lacrosse", "hiking", 
            "skateboarding", "climbing", "ultimate", "handball", "frisbee", "billiards", "snooker", "darts", 
            "shuffleboard", "bowling", "fencing", "table tennis", "dodgeball", "parkour", "rollerblading", 
            "roller skating", "yoga", "pilates", "martial arts", "crossfit", "aerobics", "jump rope", 
            "kickboxing", "zumba", "stretching", "powerlifting", "strength training", "triathlon", "equestrian", 
            "mountain biking", "judo", "taekwondo"
        ],
        "medium": [
            "pole vault", "pole dancing", "archery", "pentathlon", "decathlon", "water polo", "freestyle skiing", 
            "snowboarding", "paragliding", "wakeboarding", "bobsled", "luger", "skeleton", "speed skating", 
            "curling", "ice dancing", "freestyle wrestling", "synchronized swimming", "modern pentathlon", 
            "field hockey", "greco-roman wrestling", "aqua cycling", "indoor cycling", "footgolf", "batminton", 
            "footvolley", "speedball", "polo", "soccer freestyle", "footbag", "swimrun", "quidditch", 
            "paddleboarding", "kiteboarding", "snowkiting", "windsurfing", "beach volleyball", "handball", 
            "kickboxing", "jiu-jitsu", "squash", "archery tag", "rugby sevens", "floorball", "canopy piloting", 
            "blobbing", "longboarding", "sumo wrestling", "motocross", "xtreme sports", "sailing", "ballooning", 
            "drag racing", "air racing", "off-road racing", "kart racing", "endurance racing", "monster trucks", 
            "arm wrestling", "bull riding", "equestrian", "race walking", "ice climbing", "bike polo", 
            "aerobatic flying", "powerboat racing", "chess boxing", "jousting"
        ],
        "hard": [
            "skydiving", "base jumping", "extreme snowboarding", "parachuting", "cliff diving", "volcano boarding", 
            "bungee jumping", "freeride skiing", "mountain unicycling", "glider piloting", "ultra marathon", 
            "rock climbing", "cave diving", "ice diving", "mountain climbing", "extreme kayaking", 
            "hot air ballooning", "hang gliding", "kitesurfing", "scuba diving", "endurance swimming", 
            "surfing big waves", "track and field", "wingsuit flying", "ironman triathlon", "alpine skiing", 
            "telemark skiing", "whitewater rafting", "dog sledding", "shark diving", "tandem skydiving", 
            "rocket racing", "water jetpacks", "mountain board cross", "extreme mountain biking", 
            "surf rock climbing", "mountain skiing", "professional bull riding", "mountain races", 
            "rally racing", "downhill biking", "extreme motocross", "speed flying", "freestyle motocross", 
            "bike extreme stunts", "flipping", "lunar mountain biking", "power kite surfing"
        ],
    },
    
    "Foods": {
        "easy": [
            "apple", "banana", "carrot", "potato", "bread", "butter", "cheese", "egg", "rice", "milk",
            "cake", "pie", "grape", "orange", "tomato", "onion", "pepper", "cucumber", "chicken", "fish",
            "beef", "pasta", "salad", "soup", "cookie", "ice cream", "juice", "water", "sandwich", "steak",
            "chocolate", "yogurt", "chips", "popcorn", "orange juice", "apple juice", "lemon", "strawberry",
            "blueberry", "watermelon", "melon", "grapefruit", "spinach", "lettuce", "caramel", "bacon", "sausage",
            "turkey", "honey", "mustard", "vinegar", "olive oil", "cereal", "toast", "banana bread", "avocado",
            "peach", "pear", "plum", "kiwi", "fig", "mango", "pineapple", "cherry", "pomegranate", "peanut",
            "almond", "cashew", "walnut", "macadamia", "pistachio", "hazelnut", "granola", "pasta salad", "meatball",
            "hot dog", "cheeseburger", "hamburger", "chili", "steak fries", "fried chicken", "baked potato", "roast",
            "curry", "gravy", "toffee", "marshmallow", "pudding", "cheesecake", "brownie", "donut", "cupcake",
            "muffin", "french fries", "taco", "burrito", "nachos", "pizza", "pasta", "spaghetti", "lasagna", "sushi"
        ],
        "medium": [
            "artichoke", "zucchini", "coriander", "sesame", "cinnamon", "parsley", "cilantro", "pesto", "saffron",
            "tahini", "wasabi", "mango chutney", "sriracha", "caper", "okra", "fennel", "endive", "gouda", "gruyere",
            "brie", "camembert", "prosciutto", "bresaola", "chorizo", "pepperoni", "burrata", "mozzarella", "quiche",
            "salmon", "scallops", "lobster", "swordfish", "mussels", "clams", "shrimp", "tilapia", "cod", "halibut",
            "venison", "goat cheese", "ricotta", "asiago", "parmesan", "chevre", "bruschetta", "croissant", "baguette",
            "pumpernickel", "ciabatta", "naan", "sourdough", "challah", "brioche", "focaccia", "tortilla", "grits",
            "paella", "risotto", "jambalaya", "gumbo", "roti", "wrap", "crepe", "paella", "gnocchi", "risotto",
            "sushi roll", "nigiri", "sashimi", "soup dumpling", "bao bun", "dim sum", "empanada", "tamale", "pierogi",
            "samosa", "latte", "espresso", "macchiato", "cappuccino", "mocha", "chai", "green tea", "matcha", "kombucha",
            "smoothie", "acai bowl", "granola bar", "energy bar", "coconut milk", "soy milk", "almond milk", "cheeseboard",
            "gouda", "parmesan", "brie", "camembert", "gruyere", "ricotta", "quinoa", "bulgur", "freekeh", "farro"
        ],
        "hard": [
            "arugula", "berbere", "caraway", "caviar", "tamarind", "sumac", "harissa", "schmaltz", "balsamic vinegar",
            "kumquat", "yuzu", "fennel pollen", "anchovy", "truffle", "ramp", "miso", "sake", "yogurt cheese", "tempeh",
            "mirin", "sriracha", "coconut aminos", "poached egg", "sous vide", "sherry vinegar", "white truffle oil",
            "rosemary", "tarragon", "ginger lily", "ghee", "black garlic", "dukkah", "mole", "chimichurri", "dashi",
            "chervil", "escarole", "tapioca", "tomatillo", "chayote", "jicama", "salsify", "rutabaga", "kohlrabi",
            "watercress", "squash blossoms", "gai lan", "fiddlehead fern", "cochineal", "guanciale", "lardo", "foie gras",
            "boudin", "mirepoix", "soffritto", "confit", "crostini", "amaretto", "maraschino", "charcuterie", "caponata",
            "soubise", "cassoulet", "vol au vent", "tartare", "souffle", "croquembouche", "blanquette", "coq au vin",
            "beurre blanc", "boudin noir", "crabmeat", "oysters Rockefeller", "bouillabaisse", "chateaubriand", "tournedos",
            "mille-feuille", "clementine", "kumquat", "peppercorn", "yogurt marinated lamb", "pheasant", "boar",
            "quail", "partridge", "wild boar", "truffle salt", "morel", "puff pastry", "stracciatella", "candied ginger",
            "zabaglione", "vermouth", "tiramisu", "panna cotta", "cannoli", "biscotti", "delicata squash", "black walnuts",
            "dandelion greens", "smoked paprika", "squash puree", "lobster bisque", "squid ink", "loup de mer",
            "sugared almonds", "mochi", "ceviche", "truffle butter", "roast venison", "braised short ribs", "paté",
            "meunière", "beurre noisette", "ziti", "farfalle", "cavatelli", "aglio e olio", "capon", "ox tail"
        ],
    },
    "Books": {
        "easy" : ["book", "page", "read", "author", "story", "novel", "cover", "library", "chapter", "title",
            "cover", "paper", "pen", "reader", "fiction", "nonfiction", "bookmark", "reading", "text", 
            "bookstore", "literature", "paragraph", "sentence", "author", "tale", "plot", "hero", 
            "villain", "prologue", "epilogue", "genre", "page", "content", "pencil", "notebook", "library", 
            "index", "quotation", "dictionary", "encyclopedia", "summary", "illustration", "sketch", "hardcover", 
            "paperback", "bookshop", "publishing", "storyline", "characters", "dialogue", "bookworm", "bookish", 
            "reading glasses", "memoir", "review", "novelty", "almanac", "pseudonym", "paperback", "edition", 
            "fictional", "reading list", "bestseller", "book club", "series", "historical fiction", "autobiography", 
            "genre", "new release", "book review", "prose", "hardcover", "memoir", "library card"
        ],
        "medium": ["metaphor", "narrative", "protagonist", "antagonist", "subplot", "literary", "epilogue", "foreshadow", 
            "cliffhanger", "descriptive", "suspense", "tone", "setting", "symbolism", "allusion", "motif", "theme", 
            "bildungsroman", "cliché", "dialogue", "memoir", "poetry", "journal", "biography", "allegory", "thesis", 
            "critique", "editing", "draft", "plotline", "dynamic character", "static character", "alliteration", 
            "hyperbole", "satire", "irony", "poem", "stanza", "rhyme", "epic", "genre-blending", "classic", "literary work", 
            "genre fiction", "nonlinear", "prose style", "structure", "syntax", "format", "composition", "literary device", 
            "narrator", "point of view", "first-person", "third-person", "omniscient", "stream of consciousness", 
            "epistolary", "flashback", "climax", "resolution", "plot twist", "tension", "metaphor", "hyperbole", 
            "soliloquy", "foreshadowing", "character arc", "structure", "perspective", "subplot", "revision", "manuscript"
        ],
        "hard": [ "anagnorisis", "bildungsroman", "dystopian", "epistemology", "hermeneutics", "intertextuality", "bildungsroman", 
            "synecdoche", "onomatopoeia", "eschatology", "pantheism", "counterfactual", "fugue", "motif", "le mot juste", 
            "transcendentalism", "intertextuality", "pastiche", "epistemic", "reification", "impressionism", "realism", 
            "metanarrative", "deconstruction", "postmodernism", "avant-garde", "poststructuralism", "narratology", 
            "teleology", "heteroglossia", "aporia", "allegorical", "semiotics", "fabula", "implosion", "prolepsis", "recursion", 
            "unreliable narrator", "hermeneutic circle", "exegetical", "exegesis", "persistence", "reification", "quixotic", 
            "disenchantment", "magical realism", "romanticism", "historicism", "urban fantasy", "speculative fiction", 
            "metafiction", "ambivalence", "epistemic break", "paradox", "alienation", "otherness", "philosophical fiction", 
            "surrealism", "existentialism", "ideology", "historical materialism", "phallocentrism", "cultural hegemony", 
            "theodicy", "chiaroscuro", "palimpsest", "nihilism", "existential crisis", "metaphysical", "immanent", "objectivism", 
            "ontology", "epistemological", "genre theory", "ethical literature", "sublime", "rhetoric", "explication", 
            "sociocultural", "metaphor", "interiority", "allegory", "ambiguity"
        ]
    }
}
